# Generated by Django 6.0.5 on 2026-05-17 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('environment', models.CharField(choices=[('PROD', 'Producción'), ('STAGE', 'Staging'), ('DEV', 'Desarrollo')], default='DEV', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('level', models.CharField(choices=[('INFO', 'Información'), ('WARNING', 'Advertencia'), ('ERROR', 'Error'), ('CRITICAL', 'Crítico')], db_index=True, max_length=10)),
                ('service_name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('is_anomaly', models.BooleanField(db_index=True, default=False)),
                ('anomaly_score', models.FloatField(default=0.0)),
                ('ai_metadata', models.JSONField(blank=True, null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='almirant.servernode')),
            ],
            options={
                'verbose_name_plural': 'Log Entries',
                'ordering': ['-timestamp'],
            },
        ),
    ]
