# Generated by Django 6.0.5 on 2026-05-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almirant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={},
        ),
        migrations.AddField(
            model_name='logentry',
            name='request_ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='servernode',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='anomaly_score',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='service_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
