# Generated by Django 6.0.5 on 2026-05-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almirant', '0002_alter_logentry_options_logentry_request_ip_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Log Entries'},
        ),
        migrations.AlterField(
            model_name='logentry',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['timestamp', 'level'], name='almirant_lo_timesta_22bb31_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['timestamp', 'is_anomaly'], name='almirant_lo_timesta_639b1d_idx'),
        ),
    ]
